name: Build image

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build-image:
    runs-on: [ubuntu-18.04]
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
      - name: Check-out code
        uses: actions/checkout@v2
      - name: Build image
        run: make
      - name: Push images to registry
        if: ${{ github.repository == 'salv-orlando/nsx-container-plugin-operator' && github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker push vmware/nsx-container-plugin-operator:latest
