name: Build and push a release image

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: [ubuntu-18.04]
    steps:
    - uses: actions/checkout@v2
    - name: Build Operator image and push to registry
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        TAG: ${{ github.ref }}
      run: |
        VERSION="${TAG:10}" make
        echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        docker push vmware/nsx-container-plung-operator:"${TAG:10}"
