name: Upload assets to release

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v4
    - name: Build assets
      env:
        TAG: ${{ github.ref }}
      run: |
        mkdir assets
        VERSION="${TAG:10}" ./hack/prepare-assets.sh ./assets
    - name: Upload openshift4 tarball
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./assets/openshift4.tar.gz
        asset_name: openshift4.tar.gz
        asset_content_type: application/octet-stream
    - name: Upload kubernetes tarball
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./assets/kubernetes.tar.gz
        asset_name: kubernetes.tar.gz
        asset_content_type: application/octet-stream

